/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Calendario: typeof import('./src/components/Calendario.vue')['default']
    Carrosel: typeof import('./src/components/Carrosel.vue')['default']
    FormCriaDocumento: typeof import('./src/components/FormCriaDocumento.vue')['default']
    FormCriaUsuario: typeof import('./src/components/FormCriaUsuario.vue')['default']
    Homescreen: typeof import('./src/components/Homescreen.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaDocumentos: typeof import('./src/components/TabelaDocumentos.vue')['default']
    TelaCriarDocumento: typeof import('./src/components/TelaCriarDocumento.vue')['default']
    TelaCriaUsuario: typeof import('./src/components/TelaCriaUsuario.vue')['default']
    TelaDocumentos: typeof import('./src/components/TelaDocumentos.vue')['default']
  }
}
